version: "2"
checks:
  similar-code:
    enable: false
  identical-code:
    enabled: false
plugins:
  eslint:
    enabled: true
exclude_patterns:
  - "src/commands/botinfo/extended.js"
  - "src/commands/botinfo/commands.js"
